<a href="https://colab.research.google.com/github/elmaazouziyassine/Python_Libraries_For_DataScience/blob/master/NumPy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Library**

### **Introduction**

##### **What is NumPy?**

NumPy is a **Python Data Science Library**. 
It stands for "**Numeric Python**" or "**Numerical Python**".

NumPy containts tools & techniques that help to solve a mathematical problem in Science & Engineering.

NumPy provides a powerful data strucutre **Array Object** that holds some benefits over **Python Lists**.



##### **How to create NumPy Array?**

In [0]:
import numpy as np

In [0]:
#Create a 1D numpy array 
x = np.array([1,2,3,4], dtype = np.int64)
print(x)

#Create a 2D numpy array
y = np.array([[1,2,3,4],[5,6,7,8]], dtype = np.int64)
print(y)

#Create a 3D numpy array
z = np.array([[[10, 11, 12],[13, 14, 15]],[[20, 21, 22],[23, 24, 25]]], dtype = np.int64)
print(z)

In [0]:
# Create a 2D empty array
empty_array = np.empty((3,2))
print(empty_array)

# Create a 2D array of ones 
ones_array = np.ones((2,2))
print(ones_array)

# Create a 2D array of zeros
zeros_array = np.zeros((2,2,))
print(zeros_array)

# Create a 2D identity array
identity_array = np.identity(3)
eye_array = np.eye(3)
print(identity_array)
print(eye_array)

In [0]:
# Create a 2D array with random values between 0 and 1
random_array = np.random.random((2,2))
print(random_array)

# Create a 2D full array
full_array = np.full((3,4),10)
print(full_array)

# Create a 2D array of evenly-spaced values (given the step value)
arange_array = np.arange(10,25,5)    # array start at 10 per steps of 5 
print(arange_array)

# Create a 2D array of evenly-spaced values (given the total number of samples)
linspace_array = np.linspace(0,3,9)  # array with 9 values that lie between 0 and 3
print(linspace_array)

[[0.54001978 0.04919767]
 [0.95813475 0.94240082]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[10 15 20]
[0.    0.375 0.75  1.125 1.5   1.875 2.25  2.625 3.   ]


### **Numpy Array vs. Python List**


#####**Less Memory**

In [0]:
import sys

# Create a 1D Python list with 1000 elements
myList = range(1000)
memory_needed_for_myList = sys.getsizeof(1)*len(myList)
print(memory_needed_for_myList)     # 28000 bytes to store my Python List

# Create a 1D Numpy array with 1000 elements
myArray = np.arange(1000, dtype=np.int32)
memory_needed_for_myArray = myArray.itemsize * myArray.size                                           
print(memory_needed_for_myArray)    # 4000 bytes to store my Numpy Array


28000
4000


To store 1000 integers:  
- if we use a Python list, we will need 28 000 bytes (28 bytes/item) of memory.
- if we use a NumPy array, we will need 4 000 bytes (4 bytes/item) of memory.

#####**Fast & Convenient**

Measure time between Python List 
processing and NumPy Array processing

In [0]:
import time
size = 1000000

myList1 = range(size)
myList2 = range(size)

myArray1 = np.arange(size)
myArray2 = np.arange(size)

start = time.time()
result_Lists = [(x+y) for x,y in zip(myList1, myList2)]
print("Processing Python Lists took: ", (time.time()-start)*1000) #1000 to co

start = time.time()
result_Arrays = myArray1+myArray2
print("Processing Numpy Arrays took: ", (time.time()-start)*1000) #1000 to co



Processing Python Lists took:  150.21944046020508
Processing Numpy Arrays took:  3.3190250396728516


### **Inspecting a Numpy Array**


An array has many attributes

In [0]:
# Create a numpy array
x = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int32)
print(x)

# Print the memory address
print(x.data)

# Print the shape
print(x.shape)

# Print the total number of elements
print(x.size)

# Print the dimension 
print(x.ndim)

# Print the data type
print(x.dtype)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2
int32


In [0]:
# Print the length of one array element in bytes
print(x.itemsize)

# Print the total consumed bytes by the array's elements
print(x.nbytes)

# Print the stride
print(x.strides)

# Print information about memory layout
print(x.flags)

# Print the length of the array
print(len(x))

# Change the data type of the array
x.astype(float)

4
32
(16, 4)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

2


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

### **NumPy Broadcasting**

Broadcasting is a mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.

How to make sure that broadcasting is successful ? : The dimensions of your arrays need to be compatible.

If the dimensions are not compatible, we will get a "ValueError".

##### **Two dimensions are compatible when they are equal**

In [0]:
x = np.ones((3,4))
print(x)
y = np.random.random((3,4))
print(y)
print (x+y)

##### **Two dimensions are compatible when one of them is equal to l**

In [0]:
x = np.ones((3,4))
print(x)
y = np.arange(4)
print(y)
print(x-y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]
[[ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]]


##### **Other cases**

In [0]:
x = np.ones((3,4))
print(x)
y = np.random.random((5,1,4))
print(y)
print (x+y)

Note : notice that in the dimension where y has size 1, and the other array has a size greater than 1 (that is, 3), the first array behaves as if it were copied along that dimension.

Note that the shape of the resulting array will again be the maximum size along each dimension of x and y: the dimension of the result will be (5,3,4)


### **NumPy Manipulation**

##### **How to subset an array?**

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x)
print(x[0])
print(x[0],x[1])
print(x[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3] [4 5 6]
2


##### **How to slice an array?**

- x[start:end] : items start through the end (but the end is not included!)
- x[start:]    : items start through the rest of the array.
- x[:end]      : items from the beginning through the end (but the end is not included!)

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[0:2])
print(x[0:2,1])

[[1 2 3]
 [4 5 6]]
[2 5]


##### **How to index an array?**


*Boolean Indexing*

Boolean indexing: Instead of selecting elements, rows or columns based on index number, the selection is done using a certain condition on array values. To specify an condition, we can use logical operators ('|' for OR, '&' for AND )

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
condition = (x>3)
print(x[condition])

[4 5 6 7 8 9]


Advanced or "Fancy" Indexing

Advanced or "fancy" indexing: We pass a list or an array of integers to specify the order of the subset of rows we want to slect out of the original array

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

# Select elements at (1,0), (0,1), (1,2) and (0,0)
print(x[[1, 0, 1, 0],[0, 1, 2, 0]])

# Select a subset of the rows and columns
print(x[[1, 0, 1, 0]])

print(x[:,[0,1,2,0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 2 6 1]
[[4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]


##### **How to transpose an array?**


In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tran_x = np.transpose(x)    # x.T
print(tran_x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


##### **How to resize an array?**


If you pass your original array together with the new dimensions, and if that new array is larger than the one that you originally had, the new array will be filled with copies of the original array that are repeated as many times as is needed.

However, if you just apply np.resize() to the array and you pass the new shape to it, the new array will be filled with zeros.

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)
print(x.size)

y = np.resize(x, (6,4))
z = x.resize((6,4))

print(y)
print(z)

(3, 3)
9
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]
 [8 9 1 2]
 [3 4 5 6]]
None


##### **How to reshape an array?**


This means that you give a new shape to an array without changing its data. The key to reshaping is to make sure that the total size of the new array is unchanged. If you take the example of array x that was used above, which has a size of 3 X 3 or 12, you have to make sure that the new array also has a size of 9.

Another operation that you might keep handy when you’re changing the shape of arrays is ravel(). This function allows you to flatten your arrays. This means that if you ever have 2D, 3D or n-D arrays, you can just use this function to flatten it all out to a 1-D array.

In [0]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)
print(x.size)

# Reshape x to (1,9)
y = x.reshape((1,9))
print(y)

(3, 3)
9
[[1 2 3 4 5 6 7 8 9]]


##### **How to append arrays?**


When we append arrays to an original array, they are “glued” to the end of that original array. 
If we want to make sure that what we append does not come at the end of the array, we might consider inserting it. Go to the next section if you want to know more.

In [0]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.append(x,y)
print(z)

a = np.random.random((2,2))
print(a)

b = np.append(a, [[2],[3]], axis=1)
print(b)

[1 2 3 4 5 6]
[[0.86861008 0.30109166]
 [0.53098253 0.96044323]]
[[0.86861008 0.30109166 2.        ]
 [0.53098253 0.96044323 3.        ]]


##### **How to insert & delete array elements?**


In [0]:
x = np.array([1,2,3])

# Insert (5,4) from index 2
y = np.insert(x, 2, (5,4))
print(y)

# Delete the value at index 1
z = np.delete(x,[1])
print(z)

[1 2 5 4 3]
[1 3]
